stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: ada-awa:latest
      registry: 127.0.0.1:34029
    when:
      event: {}
- name: Test
  steps:
  - runScriptConfig:
      image: twdroeger/ada-awa:latest
      shellScript: make test
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 100
notification: {}
