stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: ada-awa
      registry: 127.0.0.1:34029
    when:
      event:
        include:
        - push
timeout: 60
notification: {}
